### ISSUE TITLE
Add Python samples?

### ISSUE THREAD

**Issue by inducer** [KhronosGroup/OpenCL-SDK#30]
At a recent CL advisory panel meeting, there was discussion about adding Python samples to the SDK. The ones I've currently collected live here:

https://github.com/inducer/pyopencl/tree/main/examples

I would say that these are of varying quality and scope. The most interesting ones are potentially these:

### Simple functionality demos

- `demo.py` ("hello-world")
- `transpose.py` (slightly nontrivial kernel)
- `dump-properties.py` (a mini-`clinfo`)
- `gl_interop_demo.py` (though I've found GL interop is pretty fragile, and I'm not currently able to test it)

### App-level demos

- `NBody.py`
- `PiXPU.py`
- `TrouNoir.py`

These represent more complete programs that were contributed by @numa65536 in https://github.com/inducer/pyopencl/pull/436. Maybe he'd be open to contributing/maintaining them here and/or adding perspective.

One concern I have about adding these examples here is CI. In the PyOpenCL repo, there is CI to ensure that these examples continue to work. If they were copied/moved here, it would be good to have a similar setup to ensure nothing breaks. The corresponding CI job is [not complicated](https://github.com/inducer/pyopencl/blob/c6e2009e068932c973ac576b5cdffea87dba81a5/.github/workflows/ci.yml#L120-L126).

**Comment by MathiasMagnus** [comment]
> One concern I have about adding these examples here is CI. In the PyOpenCL repo, there is CI to ensure that these examples continue to work.

Then we agree. If something doesn't have CI, from a practical standpoint it doesn't exist. We are aiming to have extensive samples coverage with both kinds of tests: simple and app-level. Even if the source samples are of varying quality and scope, having them as inspiration to tap into is much appreciated.

**Comment by inducer** [comment]
Great to hear. What would the next steps be? File a PR here that adds these and a CI job?

**Comment by inducer** [comment]
@numa65536 Thanks for your response, and for your willingness to help. Also, I should have explained the context better. (Sorry!) This is not about a new approach at all. To my mind, the purpose of this SDK is simply to have a collection of examples of OpenCL in use, similar to what some vendors provide for their APIs. The idea is to help potential users get started by being able to draw inspiration from existing examples.

In this case, my view is that we would simply include some examples of the use of PyOpenCL here in order to give potential users a glimpse of that "way of doing business". From your end, this shouldn't look any different from having the same code live in PyOpenCL's examples.

**Comment by inducer** [comment]
Before I go open a PR for this: what would a good path for these examples be? The existing structure appears to be very CMake-centric. Is it OK if I just make a "python/core" folder at the top level and add things there?

**Comment by MathiasMagnus** [comment]
@inducer I believe opening a PR is adequate, as that's where the nitpicking happens (in all repos). Having Python samples is a wanted feature, that's been established. Getting the basics right will be done through code review. IMHO `python/core` seems appropriate.

Since Python samples don't require building in the same sense C/C++ samples do, building doesn't need to be hooked up to CMake. However, _if_ execution will be tested (even if not result verification, just checking that they don't crash), I would be against involving any other testing framework which aren't present in other OpenCL repos (mainly CTest) where they can't get the job done.

**Comment by Kerilk** [comment]
Thanks for submitting python samples @inducer!

I plan on submitting Ruby samples and am prototyping a pull request here:
https://github.com/Kerilk/OpenCL-SDK/pull/1
I think we need at least a `samples/bindings` directory or a top level `bindings` directory.

I did some CI on Ubuntu with pocl, and a few with MacOS, but apparently they broke their CPU Opencl in the latest security patch from the 28 of April, and building programs fails... Anyway for now I built dedicated CI runs for ruby. I think I can come up with a matrix that would cover all ruby CI tests in the end.

**Comment by inducer** [comment]
> I think we need at least a `samples/bindings` directory or a top level `bindings` directory.

Personally, I think I'd prefer exposing all the bindings at the top level, with `python`, `ruby` as individual directories. If they're hidden under `bindings`, it just makes them less discoverable.

**Comment by inducer** [comment]
> I did some CI on Ubuntu with pocl, and a few with MacOS, but apparently they broke their CPU Opencl in the latest security patch from the 28 of April, and building programs fails... Anyway for now I built dedicated CI runs for ruby. I think I can come up with a matrix that would cover all ruby CI tests in the end.

I am hoping to  use https://github.com/conda-forge/ for CI. It's [three-odd commands](https://documen.tician.de/pyopencl/misc.html) to get a working CL install. Are the ruby CL bindings packaged for conda-forge?

**Comment by Kerilk** [comment]
> > I think we need at least a `samples/bindings` directory or a top level `bindings` directory.
> 
> Personally, I think I'd prefer exposing all the bindings at the top level, with `python`, `ruby` as individual directories. If they're hidden under `bindings`, it just makes them less discoverable.

I was worried about cluttering the base folder, but you are probably right.

> I am hoping to use https://github.com/conda-forge/ for CI. It's [three-odd commands](https://documen.tician.de/pyopencl/misc.html) to get a working CL install. Are the ruby CL bindings packaged for conda-forge?

I install them using gem:
https://github.com/Kerilk/OpenCL-SDK/blob/0cf14269eec269a3cbb0de18844bd271c5034499/.github/workflows/presubmit.yml#L68-L69
ruby's own installer, but I am open to other mode of distribution.

**Comment by numa65536** [comment]
So, if I understand clearly your message, you just want me to put my
examples I provided in examples of PyOpenCL in
https://github.com/Kerilk/OpenCL-SDK/tree/0cf14269eec269a3cbb0de18844bd271c5034499/samples
in order to give use cases of PyOpenCL. I suppose it would be better if I
introduce some explanations about the context, the use and the results of
the 3 examples I provided.
For example, would you like some explanations like these ones ?
- PiXPU.py illustrates the Parallel Rate influence of a single job and that
it's necessary to divide the job to do by a specific number, depending of
the GPU or CPU, to get the best performance (it's also a prime number
detector ;-) ). RNG using integers and explorations on different kinds of
variables It's also a coarse grain code, with very reduced memory
fingerprint and low memory access
- NBody.py shows the artefacts between different implementaions of OpenCL
and results. User can visualise with OpenGL the resulsts and swap between
speed and positions of particles. It's a fine grain code with low memory
fingerprint but high memory stress.
- TrouNoir.py (probably better to rename it BlackHoleAccretion.py) is the
porting of C code, heriting from Fortran 77 code. I explore several
strategies of parallelization of simulation and it's available in OpenCL
and CUDA. The memory fingerprint can overload any GPU by generating
billions pixels images. I largelly use it to compare 30 years of CPU and
GPU 2 years ago.
https://www.linkedin.com/pulse/episode-3-la-g%C3%A9pufication-dun-code-pour-simuler-un-trou-quemener
or the conference done in january 2020 :
http://www.cbp.ens-lyon.fr/emmanuel.quemener/documents/CRAL-200131.pdf

For these 3 examples, the initial goal was to compare performances (so
metrology included) and portabilty for all OpenCL devices and
implementations.

In fact, I oftenly use these 3 codes as "Matrix" codes : is this that your
have in mind ? Showing that sample codes can be used to start a project
(using perturbation method).

If you confirm that I have understood your wishes correctly, I will put my
examples is a specific folder, for example, samples/python/reallife or
samples/python/metrology

Le mer. 12 mai 2021 à 19:23, Andreas Klöckner ***@***.***> a
écrit :

**Comment by Kerilk** [comment]
> So, if I understand clearly your message, you just want me to put my examples I provided in examples of PyOpenCL in https://github.com/Kerilk/OpenCL-SDK/tree/0cf14269eec269a3cbb0de18844bd271c5034499/samples

No I don't think so, I just wanted to open the discussion so that we would create pull requests with some coherency. But I see @inducer has open one already:
https://github.com/KhronosGroup/OpenCL-SDK/pull/31
I will refactor mine to match the same architecture.

**Comment by inducer** [comment]
I think #31 is ready for a first look. No idea if the CI passes. I've left @numa65536's app-level examples out for now to avoid complicating the copyright assignment process. Maybe he can add these later (perhaps in the versions from https://github.com/inducer/pyopencl/pull/470)

**Comment by bashbaug** [comment]
Since we've merged the first round of python samples (see #31) can we close this issue?
