### ISSUE TITLE
 Could NOT find X11 (missing: X11_X11_LIB)

### ISSUE THREAD

**Issue by liu-xiao-ping** [KhronosGroup/OpenCL-SDK#47]
Hello! :
On Linux, I downloaded opencl-SDK and encountered a problem when compiling:
-- Could NOT find X11 (missing: X11_X11_LIB)
CMake Error at cmake/Dependencies/X11/X11.cmake:6 (message):
X11 Development Files not found. Please install them using your system
Package Manager, for eg. Libx11-dev
Call Stack (most recent call first):
Cmake/Dependencies. Cmake: 10 (include)
CMakeLists. TXT: 49 (include)
But I installed the libx11 - dev, rely on is still not found, OpenCL - SDK/cmake/Dependencies/X11

**Comment by MathiasMagnus** [comment]
As the error message suggests:

> X11 Development Files not found. Please install them using your system Package Manager, for eg. Libx11-dev

The SDK by default builds all samples, including the OpenCL-OpenGL interop samples, which depend on OpenGL development packages, which in turn depend on your system's windowing library. The SDK does a best effort at fetching all missing dependencies, however we cannot reasonably try to assemble/fetch development files for every desktop environment out there, some things _have_ to be fetched using system package managers. (MacOS and Windows are less fragmented, the platform SDK is enough there, this issue is Linux-specific.)

If you are not interested in building sample code, you may pass `-D OPENCL_SDK_BUILD_SAMPLES=OFF` when configuring your build to omit building all samples. If you only want to omit the more dependency-heavy OpenGL samples, then just pass `-D OPENCL_SDK_BUILD_OPENGL_SAMPLES=OFF`. All options are at the top of the CMake makefile, [here](https://github.com/KhronosGroup/OpenCL-SDK/blob/ff44fc38e298ff883716c4cc67a9976eb5205570/CMakeLists.txt#L26-L27).

_(In case you've installed your system's X11 development packages and the build still won't find them, please re-open the issue to let us know the automatic dep fetching has some shortcomings.)_

**Comment by liu-xiao-ping** [comment]
Ok, thank you. I just wanted to build Opencl.so, as you suggested: cmake -d OPENCL_SDK_BUILD_SAMPLES=OFF -d OPENCL_SDK_BUILD_OPENGL_SAMPLES=OFF. But I ran into another compilation problem:
CMake Error at _deps/freetype-external-src/CMakeLists.txt:222 (message):
In-source builds are not permitted! Make a separate folder for building,
E.g.,
Cmake - E make_directory build
Cmake -e chdir build cmake..
Before that, remove the files created by this failed run with
Cmake - E remove CMakeCache. TXT
Cmake - E remove_directory CMakeFiles
-- Configuring incomplete, errors occurred!

vim _deps/freetype-external-src/CMakeLists.txt +222

`221 if ("${CMAKE_BINARY_DIR}" STREQUAL "${CMAKE_SOURCE_DIR}")
222   message(FATAL_ERROR
223     #"CMAKE_BINARY_DIR=${CMAKE_BINARY_DIR} CMAKE_SOURCE_DIR=${CMAKE_SOURCE_DIR}\n"
224     "In-source builds are not permitted!  Make a separate folder for"
225     " building, e.g.,\n"
226     "  cmake -E make_directory build\n"
227     "  cmake -E chdir build cmake ..\n"
228     "Before that, remove the files created by this failed run with\n"
229     "  cmake -E remove CMakeCache.txt\n"
230     "  cmake -E remove_directory CMakeFiles")
231 endif ()
`

I don't know if there is a problem with the dependent freetype version, so how do I get it to compile?

**Comment by MathiasMagnus** [comment]
This a sample command-line I issued on a blank instance of Ubuntu 20.04 running in WSL.
```
sudo apt update
sudo apt install git cmake g++ build-essential -y
git clone https://github.com/KhronosGroup/OpenCL-SDK.git
git -C OpenCL-SDK/ submodule init
git -C OpenCL-SDK/ submodule update
cmake -D CMAKE_BUILD_TYPE=Release -D OPENCL_SDK_BUILD_SAMPLES=OFF -S OpenCL-SDK/ -B OpenCL-SDK/build
cmake --build OpenCL-SDK/build/ --parallel `nproc`
cmake --install OpenCL-SDK/build/ --prefix OpenCL-SDK/install
```
This is as minimal as it gets. I checked, and `apt show libx11-dev | grep installed` returns nothing, so graphical dev packages aren't installed.

Judging by your comment, I think you used `-d` instead of `-D` option to pass arguments to CMake. That doesn't work, as the CMake CLI is case sensitive. Freetype started being fetched because you didn't really disable building tests.

In case you're using CMake older than 3.15, specifying the install location can only be done through a config-time variable. In that case, issue:
```
cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=OpenCL-SDK/install -D OPENCL_SDK_BUILD_SAMPLES=OFF -S OpenCL-SDK/ -B OpenCL-SDK/build
cmake --build OpenCL-SDK/build/ --parallel `nproc` --target install
```
