### ISSUE TITLE
Remove the symlink in the releases sources

### ISSUE THREAD

**Issue by A2va** [KhronosGroup/OpenCL-SDK#82]
On Windows, without activate the developer mode it cannot extract an archive that have symlink inside. So I propose to modify the release workflow to move the content of submodule in place of the symlink.

![image](https://github.com/KhronosGroup/OpenCL-SDK/assets/49582555/9ef3fbd7-730b-4835-a241-db165e840b18)

**Comment by bashbaug** [comment]
Discussed in the November 7th teleconference.  @MathiasMagnus will take a look.

**Comment by MathiasMagnus** [comment]
I think what could be the reason for that is that we [don't recursively clone submodules](https://github.com/KhronosGroup/OpenCL-SDK/blob/d405836c85740c3a399f78c059600f4ae9605d5c/.github/workflows/release.yml#L21-L25) during the release process and the transitive submodules remain symlinks. We never see those warning, because most devs (I guess much like GitHub Actions) has [Developer Mode](https://learn.microsoft.com/en-us/windows/apps/get-started/developer-mode-features-and-debugging) enabled and thus symlink creation goes without hiccups.

We may patch up the released source tarballs retroactively, but definitely fix for future releases.

**Comment by bashbaug** [comment]
Recording a conversation from Slack:

I think the problematic symlinks are unrelated to submodules.  Here is what I see:

```sh
$ ls -lR . | grep '^l'
lrwxrwxrwx 1 bashbaug bashbaug 32 Dec 14 13:22 CL -> ../../external/OpenCL-Headers/CL
lrwxrwxrwx 1 bashbaug bashbaug 38 Dec 14 13:22 CL -> ../../external/OpenCL-CLHPP/include/CL
lrwxrwxrwx 1 bashbaug bashbaug 22 Dec 14 13:22 CL -> ../../utils/include/CL
```

These symlinks come specifically from:

```sh
./include/api:
total 0
lrwxrwxrwx 1 bashbaug bashbaug 32 Dec 14 13:22 CL -> ../../external/OpenCL-Headers/CL
./include/cpp:
total 0
lrwxrwxrwx 1 bashbaug bashbaug 38 Dec 14 13:22 CL -> ../../external/OpenCL-CLHPP/include/CL
./include/utils:
total 0
lrwxrwxrwx 1 bashbaug bashbaug 22 Dec 14 13:22 CL -> ../../utils/include/CL
```

I can't see anywhere that these symlinks are used, and the destination for the last one doesn't even exist, so I think they can just be removed.
